In [4]:
#创建指定范围的向量
import torch
t1=torch.arange(0,10,2)
print(t1)
t2=torch.linspace(1,10,4)
print(t2)

tensor([0, 2, 4, 6, 8])
tensor([ 1.,  4.,  7., 10.])


In [5]:
#创建随机张量
torch.initial_seed()
t1=torch.rand(2,3)
print(t1)

tensor([[0.0139, 0.2425, 0.8858],
        [0.3292, 0.2526, 0.4046]])


In [6]:
torch.manual_seed(100)
t2=torch.rand(2,3)
print(t2)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])


In [4]:
# 1. 第一步：必须先导入 PyTorch 库
import torch

# 2. 正确创建二维张量(把两个列表放在一个大列表中)
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

# 3. 执行逐元素乘法（* 是逐元素乘，不是矩阵乘法/点乘）
t3 = t1.mul(t2)
print(t3)

tensor([[ 7, 16, 27],
        [40, 55, 72]])


In [7]:
#演示矩阵乘法
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
t2 = torch.tensor([[7, 8], [9, 10], [11, 12]])
t3 = t1@t2
t4=t1.matmul(t2)
print(t3)
print(t4)

tensor([[ 58,  64],
        [139, 154]])
tensor([[ 58,  64],
        [139, 154]])


In [15]:
import torch
t1=torch.tensor([[1,2,3],
                 [4,5,6]
                 ])
print(t1.sum(dim=0))  #按列求和
print(t1.sum(dim=1))  #按行求和
print(t1.sum())   #全局求和
print(t1.max(dim=0)) #按列求最大值
print(t1.max(dim=1)) #按行求最大值
print(t1.max()) #全局求最大值
print(t1.pow(0))
print(t1.pow(1))
print(t1.pow(2))

tensor([5, 7, 9])
tensor([ 6, 15])
tensor(21)
torch.return_types.max(
values=tensor([4, 5, 6]),
indices=tensor([1, 1, 1]))
torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))
tensor(6)
tensor([[1, 1, 1],
        [1, 1, 1]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])


In [26]:
#演示张量的索引操作
torch.manual_seed(100)
t1=torch.randint(1,10,(3,3))
print(t1)
print(t1[0])
print(t1[1,:])
print(t1[[0,1],[1,1]])
print(t1[[[0],[1]],[1,2]]) #获取第0，1行的1，2列元素
print(t1[:3,:2])  #获取前3行，前2列元素
print(t1[1:,0:2]) #获取第2行到最后一行，前两列的元素
print(t1[t1[:,2]>5]) #获取第三列元素大于5的行元素
print(t1[1::2,::2])  #所有的奇数行，偶数列元素

tensor([[8, 8, 9],
        [9, 2, 8],
        [7, 2, 7]])
tensor([8, 8, 9])
tensor([9, 2, 8])
tensor([8, 2])
tensor([[8, 9],
        [2, 8]])
tensor([[8, 8],
        [9, 2],
        [7, 2]])
tensor([[9, 2],
        [7, 2]])
tensor([[8, 8, 9],
        [9, 2, 8],
        [7, 2, 7]])
tensor([[9, 8]])


In [8]:
#定义函数，演示reshape函数
#定义一个2行3列的矩阵
import torch
t1=torch.randint(1,10,(2,3))
print(t1)
print(t1.shape)
print(t1.reshape(3,2))

tensor([[9, 8, 5],
        [2, 3, 7]])
torch.Size([2, 3])
tensor([[9, 8],
        [5, 2],
        [3, 7]])


In [16]:
#定义函数，演示unsqueeze函数
#定义一个2行3列的矩阵
import torch
t1=torch.randint(1,10,(2,3))
print(t1)
print(t1.shape)
t2=t1.unsqueeze(1)
print(t2)
print(t2.shape)
t3=torch.randint(1,10,(2,1,3,1,1))
print(t3)
print(t3.shape)
t4=t3.squeeze()
print(t4)

tensor([[7, 5, 1],
        [2, 8, 5]])
torch.Size([2, 3])
tensor([[[7, 5, 1]],

        [[2, 8, 5]]])
torch.Size([2, 1, 3])
tensor([[[[[2]],

          [[7]],

          [[1]]]],



        [[[[8]],

          [[9]],

          [[8]]]]])
torch.Size([2, 1, 3, 1, 1])
tensor([[2, 7, 1],
        [8, 9, 8]])


In [20]:
#定义函数，演示transpose()函数,permute函数
import torch
t1=torch.randint(1,10,(2,3,4))
print(t1)
t2=t1.transpose(0,1)  #维度改为3,2,4
print(t2)
t3=t1.permute(2,0,1)  #维度改为4,2,3
print(t3)

tensor([[[6, 8, 4, 9],
         [9, 9, 1, 5],
         [8, 7, 5, 7]],

        [[2, 4, 6, 1],
         [8, 9, 3, 7],
         [3, 4, 1, 5]]])
tensor([[[6, 8, 4, 9],
         [2, 4, 6, 1]],

        [[9, 9, 1, 5],
         [8, 9, 3, 7]],

        [[8, 7, 5, 7],
         [3, 4, 1, 5]]])
tensor([[[6, 9, 8],
         [2, 8, 3]],

        [[8, 9, 7],
         [4, 9, 4]],

        [[4, 1, 5],
         [6, 3, 1]],

        [[9, 5, 7],
         [1, 7, 5]]])


In [29]:
import torch

# 原张量：形状(2,3,4)，总元素24
t1 = torch.randint(1, 10, (2, 3, 4))
print("原张量形状:", t1.shape)
print("原张量是否连续:", t1.is_contiguous())  # 输出 True

# 正确：变换为(3, 8)，3×8=24，元素数匹配
t2 = t1.view(3, 8)
print("\n变换后张量形状:", t2.shape)
print("变换后张量:\n", t2)
print("变换后张量是否连续:", t2.is_contiguous())

原张量形状: torch.Size([2, 3, 4])
原张量是否连续: True

变换后张量形状: torch.Size([3, 8])
变换后张量:
 tensor([[9, 2, 4, 9, 1, 5, 2, 9],
        [6, 4, 5, 2, 1, 5, 2, 3],
        [2, 6, 9, 4, 5, 2, 5, 8]])
变换后张量是否连续: True


In [41]:
#定义函数，演示cat()函数,stack()函数
import torch
t1=torch.randint(1,10,(2,3))
t2=torch.randint(1,10,(2,3))
t3=torch.cat([t1,t2],dim=0)
print(t3)
t4=torch.stack([t1,t2],dim=2)
print(t4)

tensor([[1, 4, 2],
        [5, 2, 6],
        [6, 9, 4],
        [4, 2, 8]])
tensor([[[1, 6],
         [4, 9],
         [2, 4]],

        [[5, 4],
         [2, 2],
         [6, 8]]])
