In [13]:
#演示创建张量
import torch
import numpy as np
t1=torch.tensor(10)
print(t1)
print(t1.dtype)
data=[[1,2,3],[4,5,6]]
t2=torch.tensor(data)
print(t2)
print(t2.dtype)
data=np.random.randint(0,10,(3,4))
t3=torch.tensor(data)
print(t3)
print(t3.dtype)

tensor([1.3313e+05, 1.7124e-42, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[4., 9., 5., 6.],
        [0., 3., 6., 9.],
        [7., 7., 3., 0.]])
torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [14]:
#演示创建张量
import torch
import numpy as np
t1=torch.Tensor(10)
print(t1)
print(t1.dtype)
data=[[1,2,3],[4,5,6]]
t2=torch.Tensor(data)
print(t2)
print(t2.dtype)
data=np.random.randint(0,10,(3,4))
t3=torch.Tensor(data)
print(t3)
print(t3.dtype)
t4=torch.Tensor(2,3)
print(t4)
print(t4.dtype)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[3., 5., 7., 9.],
        [6., 0., 3., 7.],
        [5., 5., 4., 4.]])
torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [17]:
#演示创建张量
import torch
import numpy as np
t1=torch.IntTensor(10)
print(t1)
print(t1.dtype)
data=[[1,2,3],[4,5,6]]
t2=torch.IntTensor(data)
print(t2)
print(t2.dtype)
data=np.random.randint(0,10,(3,4))
t3=torch.IntTensor(data)
print(t3)
print(t3.dtype)
t4=torch.FloatTensor(2,3)
print(t4)
print(t4.dtype)

tensor([1208093808,       1222,          0,          0,          0,          0,
                 0,          0,          0,          0], dtype=torch.int32)
torch.int32
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)
torch.int32
tensor([[1, 0, 2, 8],
        [6, 7, 0, 5],
        [8, 7, 3, 3]], dtype=torch.int32)
torch.int32
tensor([[1.3520e+05, 1.7124e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
torch.float32
