In [1]:
import numpy as np
from numpy.conftest import dtype

nested_list = [[1,2.5,3],[4,5,6.0]]
a = np.array(nested_list)
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)

[[1.  2.5 3. ]
 [4.  5.  6. ]]
float64
2
(2, 3)


In [9]:
import numpy as np
a = np.zeros((3,2), dtype=int)
print(a)
b = np.ones((2,2,3),dtype=float)
print(b)

[[0 0]
 [0 0]
 [0 0]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [16]:
import numpy as np
a = np.arange(4)
print(a)
b = np.linspace(0,1,4,dtype=float)
print(b)

[0 1 2 3]
[0.         0.33333333 0.66666667 1.        ]


In [17]:
import numpy as np
a = np.eye(4,5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [26]:
import numpy as np
a = np.arange(9)
print(a)
b = a.reshape(3,3)
print(b)
c = a.flatten()
print(c)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]


In [1]:
import numpy as np
np1=np.zeros((3,4),dtype=float)
print(np1)
np2=np.eye(5,dtype=int)
print(np2)
np3=np.arange(2,32,3)
print(np3)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[ 2  5  8 11 14 17 20 23 26 29]


In [7]:
import numpy as np
np1=np.random.randn(2,3)
print(np1)
np2=np.random.rand(5,)
print(np2)
np3=np.linspace(1,2,10)
print(np3)

[[-0.84910923 -0.9214845   1.2405778 ]
 [-0.71804891 -0.66344432 -0.84428874]]
[0.15553989 0.50758573 0.03948958 0.09199213 0.38029681]
[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [15]:
import numpy as np
np1=np.ones((3,4),dtype=int)
np2=np.arange(0,24,2)
np3=np2.reshape((3,4))
print(np1+np3)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]
